import prisma from "../config/db.js";

const allSubjects = [
  // FOUNDATION - Mathematics
  { code: "BCS ZC219", name: "Discrete Mathematics", units: 3, semester: 1, term: 1, category: "FOUNDATION", description: "Sets & operation on sets; relations, functions, Recursive functions, sequences and summations, Mathematical Induction, Proof Methods (direct, indirect, proof by contradiction), principle of inclusion & exclusion, pigeonhole principle; Permutations and Combinations; Recurrence Relations; basic algebraic structures and their applications. Introduction to graphs, properties and applications", prerequisites: [] },
  { code: "BCS ZC230", name: "Linear Algebra and Optimization", units: 3, semester: 1, term: 1, category: "FOUNDATION", description: "Vector and matrix algebra, systems of linear algebraic equations and their solutions; eigenvalues, eigenvectors and diagonalization of matrices; Formulation of linear programming problems, Simplex method, Big-M method, two phase method, Sensitivity analysis, Revised and Dual Simplex Methods.", prerequisites: [] },
  { code: "BCS ZC233", name: "Probability and Statistics", units: 3, semester: 2, term: 1, category: "FOUNDATION", description: "Probability spaces; conditional probability and independence; random variables and probability distributions; marginal and conditional distributions; independent random variables; mathematical expectation; mean and variance; binomial, Poisson and normal distributions; sum of independent random variables; law of large numbers; central limit theorem (without proof); sampling distribution and test for mean using normal and student's t-distribution; test of hypothesis; correlation and linear regression.", prerequisites: [] },
  { code: "BCS ZC112", name: "Introduction to Logic", units: 2, semester: 2, term: 1, category: "FOUNDATION", description: "Propositional logic – syntax, semantics, natural deduction, satisfiability & validity, predicate or first order logic – syntax, semantics, proof theory satisfiability & validity, completeness & compactness, proof techniques, Undecidability & incompleteness; Godel's incompleteness theorem; overview of applications in program verification, knowledge representation.", prerequisites: [] },
  // Science & Eng - Option 1 ($)
  { code: "BCS ZC223", name: "General Biology", units: 3, semester: 2, term: 2, category: "FOUNDATION_OPTION", foundationOption: 1, description: "Living systems and their properties; major biological compounds; basic physiological processes; introduction to genetics; environment and evolution.", prerequisites: [] },
  { code: "BSC ZC240", name: "General Physics", units: 3, semester: 2, term: 2, category: "FOUNDATION_OPTION", foundationOption: 1, description: "Philosophy of Science; Newton's laws of motion; Work Energy, Impulse and Momentum; Equilibrium; Moment of a force; Rotation; Periodic motion; First law of thermodynamics; Second law of thermodynamics; Electromagnetic waves; Interference and diffraction; Polarization; Relativistic mechanics; Photons, Electrons and Atoms; Quantum Mechanics; Atoms, Molecules and Solids; Nuclear Physics.", prerequisites: [] },
  { code: "BCS ZC111", name: "Basic Electronics", units: 2, semester: 1, term: 1, category: "FOUNDATION", description: "Course covers basic passive circuit elements, dependent and independent sources, network theorems, circuit analysis techniques and response of first and second order circuits. Semiconductors - operation of diodes, bipolar junction transistors and field effect transistors. Biasing techniques and transistors. Introduction to operational amplifiers and applications.", prerequisites: [] },
  // Humanities - Option 2 (#)
  { code: "BCS ZC113", name: "Online Social Media", units: 2, semester: 3, term: 1, category: "FOUNDATION_OPTION", foundationOption: 2, description: "Social media - evolution, definition, classification, Present social media landscape; Different kinds of online community and social structure; benefits of social media for individuals, business and society; impacts of people and artificial intelligence on social media; Impacts of Social media - personal, professional, social aspects with cases; Concerns (Privacy, authenticity, Informed Consent, Anonymity, Risks), Safety.", prerequisites: [] },
  { code: "BCS ZC114", name: "Video Games - Technology and Social Impacts", units: 2, semester: 3, term: 1, category: "FOUNDATION_OPTION", foundationOption: 2, description: "Video Games- introduction, play and game- deconstructing video games: narrative structures of videogames, critiquing rules in videogames, immersion and materiality- puzzles, drama and socio-technical system of video games- Themes of videogames: violence, addiction, language, sexuality, gender, identity, communities, values and ethics, game genres: e-sports, indie games, serious games-gamification, game design.", prerequisites: [] },
  // Other
  { code: "BCS ZC151", name: "Writing Practice", units: 3, semester: 1, term: 1, category: "FOUNDATION", description: "Introduction to academic writing – Purpose, Type, Features, Originality, integrity and plagiarism; Paragraph writing – Structure, Development of ideas, Linking paragraphs together, Introduction, opening sentence and conclusion; Elements of writing – Argument and discussion, Cause and effect, Comparison, Generalizations, Problems and solution, Process writing, Visual information, Accuracy in writing, Academic vocabulary, Caution, Conjunction/Linkers/Signposting, Punctuation, Passives, Tense forms, Summarizing and paraphrasing; Writing models - E-mails (formal), Short essays (2-paragraph essay, thesis statement), and Reports (Introduction, Methods, Results, Conclusion, Abstract).", prerequisites: [] },
  { code: "BCS ZC220", name: "Environmental Studies", units: 3, semester: 4, term: 1, category: "FOUNDATION", description: "Environment, human population, and industrialization; natural resources and the impact of man-made activities on them; structure and function of ecosystem, population ecology, biodiversity and its conservation, environmental pollution, social issues and the environment, and environmental impact assessment.", prerequisites: [] },
  { code: "BCS ZC229", name: "Introduction to Economics", units: 3, semester: 6, term: 1, category: "FOUNDATION_OPTION", foundationOption: 3, description: "Big ideas in economics; Functioning of the economy; Scarcity and choice; Consumer behaviour; Firm behaviour; Competitive markets; Labour markets; Unemployment; Capital market; Banking and the non-banking financial institution; Central banking; Economic growth; Inflation; Monetary policy; Fiscal Policy.", prerequisites: [] },
  { code: "BCS ZC235", name: "Science, Technology and Modernity", units: 3, semester: 6, term: 1, category: "FOUNDATION_OPTION", foundationOption: 3, description: "Science, Technology and Modernity - Explores relationship between science, technology and society; impacts of technological change on modernity, ethics, sustainability and social structures.", prerequisites: [] },
  { code: "BCS ZC239", name: "Writing Practice", units: 3, semester: 1, term: 1, category: "FOUNDATION", description: "Introduction to academic writing – Purpose, Type, Features, Originality, integrity and plagiarism; Paragraph writing – Structure, Development of ideas, Linking paragraphs together, Introduction, opening sentence and conclusion; Elements of writing – Argument and discussion, Cause and effect, Comparison, Generalizations, Problems and solution, Process writing, Visual information, Accuracy in writing, Academic vocabulary, Caution, Conjunction/Linkers/Signposting, Punctuation, Passives, Tense forms, Summarizing and paraphrasing; Writing models - E-mails (formal), Short essays (2-paragraph essay, thesis statement), and Reports.", prerequisites: [] },
  // CORE
  { code: "BCS ZC313", name: "Introduction to Programming", units: 4, semester: 1, term: 1, category: "CORE", description: "Basic representation of data and how to process data using the representation inside a computer. Techniques for specifying data, operations on data, and problem-solving using C programming language. Systematic techniques and approaches for constructing programs.", prerequisites: [] },
  { code: "BCS ZC228", name: "Introduction to Computing Systems", units: 3, semester: 1, term: 1, category: "CORE", description: "This course teaches a beginner what a computer is and how it can be programmed. The course starts with basic building blocks required to understand the structure of a computer: numbers, bits, structures to implement operations on numbers, and structures to control the execution of commands by a computer. The course progresses to introduce logic gates, and combinational and sequential circuits. It introduces a simple processor design with a small instruction set architecture and basic assembly programming with that processor.", prerequisites: [] },
  { code: "BCS ZC216", name: "Computer Systems and Performance", units: 3, semester: 3, term: 1, category: "CORE", description: "Processor Architecture (Instruction Set Level)- Different types of instructions AL, Memory Access, Branch/Jump; Straight Line Programs vs. Branches: Different Loop Structures, Performance of Loops, Nested Conditionals, Inner Loops – Examples; Cost of Procedure Calls vs. goto statements; Memory Hierarchy: Motivation – Cost vs. Size vs. Access Time. Main Memory and Cache. Write-through vs. Write-back Cache. Access Time Calculation and Hit Ratio; Locality of Reference; Paging (of Main Memory) and Page Faults, Performance Impact; Procedure Calls and Space; Hard Disks and Disk Access (Disk Access Time vs. RAM access Time.); Disk IO and File IO, Buffered vs. Unbuffered IO. Performance: Read vs. Write vs. Read-and-Write; Disk Locality. Sequential Access vs. Random Access in Files - Examples; Flash / SSD Storage: SSD access and access times; Write limitations; Flash File Systems; Performance Impact.", prerequisites: [] },
  { code: "BCS ZC215", name: "Command Line Interfaces and Scripting", units: 3, semester: 2, term: 1, category: "CORE", description: "Files and Directory, internals of a file system, inode structure, block I/O; File commands, pipes and filters, programming with commands; Shell and interpretation of commands, programming with shell scripts, feature usage, interaction with I/Os; Systems calls, usage with C Programming, file system and I/O calls.", prerequisites: [] },
  { code: "BCS ZC311", name: "Data Structures and Algorithms", units: 4, semester: 2, term: 1, category: "CORE", description: "Introduction to Asymptotic Notations, Solving Recurrences (substitution method, iteration method, master theorem), Abstract Data Types, Linear Data Structures (Stacks, Queues, and Linked Lists), Non-Linear Data Structures-Heap, Hash Tables, Binary Search Trees, Balanced Binary Search Trees, Sorting Algorithms (insertion sort, selection sort, merge sort), Graph Data Structures (Adjacency List and Adjacency Matrix), Graph Traversal algorithms, Topological sort, Strongly connected components.", prerequisites: [] },
  { code: "BCS ZC212", name: "Algorithm Design", units: 3, semester: 3, term: 1, category: "CORE", description: "Effective construction and analysis of algorithms. Understanding, application, and implementation of algorithm design techniques like divide-and-conquer, greedy, dynamic programming, and back-tracking. Worst case and average case analysis of algorithms. Basic notions of complexity classes – P, NP, and NP-complete and Reduction.", prerequisites: [] },
  { code: "BCS ZC316", name: "Object Oriented Programming", units: 4, semester: 2, term: 1, category: "CORE", description: "Object orientation concepts, theories and principles; fundamental concepts of the object model: classes, objects, methods and messages, encapsulation and inheritance, interface and implementation, reuse and extension of classes, inheritance and polymorphism; overloading and overriding; static and dynamic binding; multithreaded programming; event handling and exception handling; process of object oriented requirements specification, analysis and design; notations for object-oriented analysis and design; case studies and applications using some object oriented programming languages. Object Oriented Design Patterns: Behavioral, Structural and Creational.", prerequisites: [] },
  { code: "BCS ZC317", name: "Relational Databases", units: 4, semester: 3, term: 1, category: "CORE", description: "Introduction to Database Management Systems; File organization; Data Independence in databases; Data Modeling; Data Definition and Manipulation; Relational Data Model; Relational Algebra & Relational Calculus; Structured Query Languages; Database Design techniques; Functional Dependencies & Normalization; Query processing and optimization; Indexing techniques; Transaction management - concurrency control and recovery; Distributed Databases; Concepts of security and integrity in databases.", prerequisites: [] },
  { code: "BCS ZC234", name: "Programming for Mobile Devices", units: 3, semester: 4, term: 1, category: "CORE", description: "Introduction to mobile computing and emerging mobile application and hardware platforms; Developing and accessing mobile applications; Software lifecycle for mobile application – design and architecture, development – tools, techniques, frameworks, deployment; Human factors and emerging human-computer interfaces (tangible, immersive, attentive, gesture, zero-input); Select application domains such as pervasive health care, m-Health; Mobile web browsing, gaming and social networking; Trends in mobile application development.", prerequisites: [] },
  { code: "BCS ZC238", name: "Web Programming", units: 3, semester: 3, term: 1, category: "CORE", description: "Technologies related to web development and associated technologies that make the web work. Scripting languages like HTML, CSS and JavaScript; Design of dynamic websites; on both client-side and server-side scripting technologies; full-stack web development. Design and development of web applications, web applications that could query database and fetch information over the network; development and testing of web applications.", prerequisites: [] },
  { code: "BCS ZC232", name: "Operating Systems", units: 3, semester: 4, term: 1, category: "CORE", description: "Introduction to operating systems; Various approaches to design of operating systems ; Overview of hardware support for operating systems; Process/thread management: synchronization and mutual exclusion, inter process communication, CPU scheduling approaches; Memory management: paging, segmentation, virtual memory, page replacement algorithms ; File systems: design and implementation of file systems; Input /Output systems; device controllers and device drivers; Security and protection; Case studies on design and implementation of operating system modules.", prerequisites: [] },
  { code: "BCS ZC236", name: "Software Design Principles", units: 4, semester: 3, term: 1, category: "CORE", description: "Software Development lifecycle; Role of high level and low level design in lifecycle. Object-Oriented Abstraction and Object Oriented Design. Design for Reuse and Design for Change – Refactoring. Design Patterns - History of Patterns in Building Architecture and Relevance to Software Design, Evolution of Software Design Patterns and Impact of Using Design Patterns in Lifecycle. Crosscutting Concerns and Aspects – Aspect Oriented Design. High-level design vs. Low-level design. Basic Architectural Elements and Styles – Layered Architectures and Event-Driven Architectures, MVC architecture in User Interfaces.", prerequisites: [] },
  { code: "BCS ZC214", name: "Building Database Applications", units: 3, semester: 4, term: 1, category: "CORE", description: "This course discusses end-to-end application programming involving databases using SQL, PL/SQL, front-end framework, and exposing back-end through APIs. Debugging, Testing, Monitoring, Documenting and Maintaining database applications are discussed. Particular focus will be on Database connectivity; stored procedures; data ingestion/loading; ingestion latency and query performance. This course culminates with a project that involves programming, implementing, and demonstrating a database solution for a business or organization", prerequisites: [] },
  { code: "BCS ZC211", name: "Software Development Practices", units: 3, semester: 5, term: 1, category: "CORE", description: "Review of Use Cases. Design using use cases and data flow; Development Tools and Technologies - IDEs (Eclipse); Compilers and Compiler Options, Libraries and APIs; Code Reviews and walkthroughs; Debugging and Unit Testing, Runtime conditions and Assertions; Runtime Environments (JVM, Android) Code Repositories (GitHub); Versioning; CI/CD.", prerequisites: [] },
  { code: "BCS ZC231", name: "Network Programming and Client-Server Programming", units: 3, semester: 5, term: 1, category: "CORE", description: "Overview of computer networks; inter-process communication; network programming; socket interface; client-server computing model: design issues, concurrency in server and clients; external data representation; remote procedure calls; network file systems; distributed systems design.", prerequisites: [] },
  { code: "BCS ZC222", name: "Formal Languages and Applications", units: 3, semester: 4, term: 1, category: "CORE", description: "Regular Expressions, Typical languages expressible using Regular expressions - Regular Languages, Closure Properties; Tokens or Lexemes of Languages (Formal or Natural) – Token descriptions, Scanning Sentences or Programs, Scanner - Design and Implementation. Applications: Specifying patterns, Test cases; Context Free Grammars and Rules, Context Free Languages; Defining the syntax of formal and natural languages; Closure Properties; Limitations of CFGS – features not expressible via CFGs; Context-sensitive Grammars and Languages; Parsing sentences or programs. LL Parsing vs LR Parsing; Look heads - LL(1) parsing, LL(1) parsing engine, and construction of LL(1) parsing table; LL(k) parsing examples and counterexamples, Issues – Ambiguity in CFGs and CFLs. Resolving Ambiguity – Left Factoring and Left Recursion. LR(1) parsing; Application – Natural Language Parsing and POS Tagging;", prerequisites: [] },
  // Electives
  { code: "BCS ZC224", name: "Graphs and Networks", units: 3, semester: 5, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Basic concepts of graphs and digraphs, Modelling problems from application domains as graph problem, connectedness, reachability, Euler Tours, Hamiltonian Cycles, planarity, Applications; real world networks: measures (centrality, transitivity, reciprocity), properties and models (random networks, small world model, preferential attachment model), communities in social networks", prerequisites: [] },
  { code: "BCS ZC213", name: "Automata and Computability", units: 3, semester: 5, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Finite Automata – DFA, Equivalence of DFAs to regular expressions; PDA – DFA with a stack, equivalence of PDAs to CFLs; Turing Machines – Comparative power of DFAs, PDAs, and TMs. Universal TM; Brief Overview of Chomsky's hierarchy and Church-Turing hypothesis; Non-computable functions; Informal equivalence between TMs and General Purpose computers. Pre-requisite: BCS ZC222", prerequisites: ["BCS ZC222"] },
  { code: "BCS ZC221", name: "Experimental Algorithmics", units: 3, semester: 5, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Review of time complexity, order of complexity, and Big-O notation; Comparing Theoretical analysis of time and space complexity of elementary algorithms (Sorting, Binary Search trees, Hash tables) with experimental running-time and space measurements. Experiments on key distribution: Measuring heights of BSTs for different datasets and order of arrivals, Uniformity of buckets/bins in hashtables with different hash functions; Size Experiments: Growth of hash table size with datasets and query sequences, Bloom filter size vs. false positive rates, Sketches and cardinality estimation via HyperLogLog. IO Complexity and disk access measurements: Sorting, BSTs vs. B-Trees, Sparse Graphs vs. Dense Graphs. Caching in Data Structures. Case Studies: Use of B-Tree variants in datasets, Bloom filters in Distributed file systems, and HyperLogLog in Redis. Pre-requisites: BCS ZC311, BCS ZC212", prerequisites: ["BCS ZC311", "BCS ZC212"] },
  { code: "BCS ZC227", name: "Introduction to Bioinformatics", units: 3, semester: 5, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Introduction to Bioinformatics - Course description to be released soon. Covers fundamentals of biological data analysis, sequence alignment, and computational biology tools.", prerequisites: [] },
  { code: "BCS ZC217", name: "Data Visualization", units: 3, semester: 5, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Information overload and issues in decision making. Design of visual encoding schemes to improve comprehension of data and their use in decision making; presentation and visualization of data for effective communication. Elementary graphics programming, charts, graphs, animations, user interactivity, hierarchical layouts, and techniques for visualization of high dimensional data & discovered patterns.", prerequisites: [] },
  { code: "BCS ZC312", name: "Introduction to Data Analytics", units: 4, semester: 5, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Introduction to data analytics, applications, Python fundamentals (variables, strings, simple math, conditional logic, for loops, lists, tuples, dictionaries, etc.); Preparing the data - download the data in python, visualizing using matplotlib, seaborn to gain insights, data cleaning, transformation; Regression - applications, fitting models, gradient descent, evaluation, regularized models); Classification - applications, fitting models ( decision tree, logistic regression), addressing overfitting, performance, Model selection techniques; Clustering - applications, k-means and hierarchical clustering, quality of clustering; Discussion on advanced topics; Ethical implications of handling data and building models. Pre-requisites: BCS ZC230, BCS ZC233, BCS ZC313", prerequisites: ["BCS ZC230", "BCS ZC233", "BCS ZC313"] },
  { code: "BCS ZC315", name: "Multicore and GPGPU Programming", units: 4, semester: 5, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Multi-threaded Programming. Review of multicore processors and caching. Shared Memory Programming in the multi-core context. – Use of Locks for Synchronization. Shared Memory data structures - Synchronization issues and models, Lazy synchronization, Design of shared memory data structures. Review of GPGPU architecture and GPGPU programming model. Programming with many-core processors and NUMA. CUDA Programming. Pre-requisite: BCS ZC216", prerequisites: ["BCS ZC216"] },
  { code: "BCS ZC237", name: "TCP/IP and Internet", units: 3, semester: 5, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Review of the OSI model and the Internet model; A top-down approach. Application Layer – HTTP, HTTPS/TLS, DNS, and Multi-media transport; The Internet – Transport, TCP vs. UDP, Routing, and Gateways. IP – Addressing and Routing. Pre-requisite: BCS ZC231", prerequisites: ["BCS ZC231"] },
  { code: "BCS ZC226", name: "Information Security", units: 3, semester: 6, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Program security, Web security, Database security, Protection in operating systems, Cloud security fundamentals; Privacy and Anonymity in computing; Legal and ethical issues in security, Secure programming and Trusted systems design; policy, administration and procedures; auditing; physical security; content protection.", prerequisites: [] },
  { code: "BCS ZC225", name: "Human Computer Interaction", units: 3, semester: 6, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Principles of human-computer interaction; Evaluation of user interfaces; Usability engineering; Task analysis, user-centred design, and prototyping; Conceptual models and metaphors; Software design rationale; Design of windows, menus, and commands. Voice and natural language I/O; Response time and feedback; Color, icons, and sound; Internationalization and localization; User interface architectures and APIs.", prerequisites: [] },
  { code: "BCS ZC218", name: "Designing Multimodal Interfaces", units: 3, semester: 6, term: 1, category: "DISCIPLINE_ELECTIVE", description: "UI Design Principles; GUI Design; Interfaces with multiple modes of interaction – text, graphics, and speech; Identification and authentication: CAPTCHAs; Smart Cards; Design of multi-factor authentication schemes; Identification in Personal Devices – fingerprints, voice-print identification; Design of interfaces for Smart Personal Assistants; Case Study: Siri/Cortana, Alexa/Google Device. Design of chatbots with emphasis on the design of Natural language interaction/conversations. Pre-requisite: BCS ZC316", prerequisites: ["BCS ZC316"] },
  { code: "BCS ZC314", name: "Modern Databases", units: 4, semester: 6, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Different types of content - Structured vs. Unstructured vs. Semi-structured data, notion of Atomicity (or Consistency) ACID vs. BASE; Strong vs. Weak Consistency model; Serializability; Eventual Consistency; CAP Theorem and Implications; Solution models and Design Examples (some of MongoDB, REDIS, Cassandra, Neo4j); Document stores, Key-Value Stores, Column stores, Graph stores and languages for their query processing, In-memory databases, and cloud databases (E.g, Amazon RDS); Exposure to application development. Pre-requisite: BCS ZC214", prerequisites: ["BCS ZC214"] },
  // Projects
  { code: "BCS ZC241T", name: "Study Project", units: 5, semester: 5, term: 1, category: "PROJECT", description: "In this course, students are expected to carry out an organized study and identify a problem which requires a software solution. Students also study the impacts of solving the problem and the existing solutions. At the end of the course, students submit a report with the project proposal, details on background, scope and solution methodology (including requirement specifications).", prerequisites: [] },
  { code: "BCS ZC428T", name: "Project", units: 10, semester: 6, term: 1, category: "PROJECT", description: "In this course, the students work to produce a software solution to a problem whose requirements were studied and documented in the Study Project course. The students will demonstrate their work and submit the detailed project report at the end of the semester.", prerequisites: [] },
  // Specialization - Full Stack
  { code: "BHCS ZC413", name: "Backend and API Development", units: 4, semester: 7, term: 1, category: "SPECIALIZATION", specialization: "FULL_STACK", isMandatory: true, description: "Backend and API Development - Design and implementation of scalable backend services, RESTful APIs, authentication, middleware, database integration with Node.js/Express and Prisma.", prerequisites: [] },
  { code: "BHCS ZC419", name: "Frontend Development", units: 3, semester: 7, term: 1, category: "SPECIALIZATION", specialization: "FULL_STACK", isMandatory: true, description: "Frontend Development - Modern frontend with React, state management with Redux Toolkit, component design, responsive UI with NativeWind/Tailwind.", prerequisites: [] },
  { code: "BHCS ZC415", name: "Cross-platform Applications", units: 3, semester: 7, term: 1, category: "SPECIALIZATION", specialization: "FULL_STACK", isMandatory: true, description: "Cross-platform Applications - Building cross-platform apps with React Native and Expo, platform-specific adaptations, native modules. Pre-requisite: Frontend Development", prerequisites: ["BHCS ZC419"] },
  { code: "BHCS ZC432", name: "Software Deployment", units: 4, semester: 7, term: 1, category: "SPECIALIZATION", specialization: "FULL_STACK", isMandatory: true, description: "Software Deployment - CI/CD, containerization, cloud deployment on Vercel/Neon, EAS builds, environment management. Pre-requisites: Backend and API Development, Frontend Development", prerequisites: ["BHCS ZC413", "BHCS ZC419"] },
  // Cloud
  { code: "BHCS ZC414", name: "Cloud Computing Fundamentals", units: 3, semester: 7, term: 1, category: "SPECIALIZATION", specialization: "CLOUD", isMandatory: true, description: "Cloud Computing Fundamentals - Introduction to cloud models, virtualization, IaaS/PaaS/SaaS, cloud economics.", prerequisites: [] },
  { code: "BHCS ZC422", name: "Introduction to Networking for Cloud", units: 3, semester: 7, term: 1, category: "SPECIALIZATION", specialization: "CLOUD", isMandatory: true, description: "Introduction to Networking for Cloud - Networking fundamentals for cloud, VPC, load balancing, DNS. Pre-requisite: BCS ZC237", prerequisites: ["BCS ZC237"] },
  { code: "BHCS ZC420", name: "Introduction to DevOps for Cloud", units: 4, semester: 7, term: 1, category: "SPECIALIZATION", specialization: "CLOUD", isMandatory: true, description: "Introduction to DevOps for Cloud - CI/CD pipelines, infrastructure as code, monitoring. Pre-requisite: Cloud Computing Fundamentals", prerequisites: ["BHCS ZC414"] },
  { code: "BHCS ZC430", name: "Scalable Services in Cloud", units: 4, semester: 7, term: 1, category: "SPECIALIZATION", specialization: "CLOUD", isMandatory: true, description: "Scalable Services in Cloud - Designing scalable, fault-tolerant cloud services, auto-scaling, distributed systems. Pre-requisite: Cloud Computing Fundamental", prerequisites: ["BHCS ZC414"] },
  // AIML
  { code: "BHCS ZC421", name: "Introduction to Machine Learning", units: 4, semester: 7, term: 1, category: "SPECIALIZATION", specialization: "AIML", isMandatory: true, description: "Introduction to Machine Learning - Supervised/unsupervised learning, model training, evaluation, Python/scikit-learn. Pre-requisite: BCS ZC312", prerequisites: ["BCS ZC312"] },
  { code: "BHCS ZC412", name: "Artificial Intelligence", units: 3, semester: 7, term: 1, category: "SPECIALIZATION", specialization: "AIML", isMandatory: true, description: "Artificial Intelligence - Search, knowledge representation, reasoning, planning, game playing.", prerequisites: [] },
  { code: "BHCS ZC417", name: "Deep Learning and Applications", units: 4, semester: 7, term: 1, category: "SPECIALIZATION", specialization: "AIML", isMandatory: true, description: "Deep Learning and Applications - Neural networks, CNNs, RNNs, transformers, applications. Pre-requisite: Introduction to Machine Learning", prerequisites: ["BHCS ZC421"] },
  { code: "BHCS ZC434", name: "Topics in Data Mining", units: 4, semester: 7, term: 1, category: "SPECIALIZATION", specialization: "AIML", isMandatory: true, description: "Topics in Data Mining - Association rules, clustering, classification at scale, big data mining. Pre-requisite: BCS ZC312", prerequisites: ["BCS ZC312"] },
  { code: "BHCS ZC427T", name: "Mini Project", units: 5, semester: 7, term: 1, category: "MINI_PROJECT", isMandatory: true, description: "Mini Project (5 units) - Hands-on project in chosen specialization domain, applying learned concepts to build a real product. Mandatory for all specializations.", prerequisites: [] },
  // Discipline electives for VII/VIII additional pool
  { code: "BHCS ZC433", name: "Topics in Algorithms and Complexity", units: 4, semester: 7, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Topics in Algorithms and Complexity - Advanced algorithmic analysis, complexity theory, approximation algorithms.", prerequisites: [] },
  { code: "BHCS ZC324", name: "Compiler Design", units: 4, semester: 7, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Compiler Design - Lexical analysis, parsing, code generation, optimization.", prerequisites: [] },
  { code: "BHCS ZG512", name: "Network Security", units: 4, semester: 7, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Network Security - Applied network security, Firewalls, IDS, VPNs. Pre-requisite: Cloud Computing Fundamentals", prerequisites: ["BHCS ZC414"] },
  { code: "BHCS ZC321", name: "Software Testing and Automation", units: 3, semester: 7, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Software Testing and Automation - Test strategies, automation frameworks, QA processes. Pre-requisite: Cloud Computing Fundamental", prerequisites: ["BHCS ZC414"] },
  { code: "BHCS ZC418", name: "Distributed Systems", units: 4, semester: 7, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Distributed Systems - Consistency, replication, consensus, distributed transactions.", prerequisites: [] },
  { code: "BHCS ZC319", name: "Natural Language Processing", units: 4, semester: 7, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Natural Language Processing - Text processing, language models, sentiment analysis.", prerequisites: [] },
  { code: "BHCS ZC423", name: "Introduction to Social Media Analytics", units: 4, semester: 7, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Introduction to Social Media Analytics - Analytics on social graphs, metrics, influence analysis. Pre-requisite: BCS ZC237", prerequisites: ["BCS ZC237"] },
  { code: "BHCS ZC416", name: "Cryptography", units: 3, semester: 7, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Cryptography - Symmetric/asymmetric crypto, hashing, PKI. Pre-requisite: Cloud Computing Fundamentals", prerequisites: ["BHCS ZC414"] },
  { code: "BHCS ZG511", name: "Agile Software Processes", units: 4, semester: 7, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Agile Software Processes - Scrum, Kanban, agile planning and execution. Pre-requisite: Cloud Computing Fundamental", prerequisites: ["BHCS ZC414"] },
  { code: "BHCS ZC429", name: "Open Source Software", units: 3, semester: 7, term: 1, category: "DISCIPLINE_ELECTIVE", description: "Open Source Software - Contributing to open source, licensing, community processes.", prerequisites: [] },
  // Open Electives VII/VIII
  { code: "BHCS ZC327", name: "Introduction to Calculus", units: 3, semester: 7, term: 1, category: "OPEN_ELECTIVE", description: "Introduction to Calculus - Limits, derivatives, integrals, applications.", prerequisites: [] },
  { code: "BHCS ZC325", name: "Differential Equations and Applications", units: 3, semester: 7, term: 1, category: "OPEN_ELECTIVE", description: "Differential Equations and Applications - First order, second order ODEs, applications.", prerequisites: [] },
  { code: "BHCS ZC320", name: "Numerical Analysis", units: 3, semester: 7, term: 1, category: "OPEN_ELECTIVE", description: "Numerical Analysis - Numerical methods for solving equations, interpolation, integration.", prerequisites: [] },
  { code: "BHCS ZC241", name: "Microprocessors, Programming and Interfacing", units: 4, semester: 7, term: 1, category: "OPEN_ELECTIVE", description: "Microprocessors, Programming and Interfacing - Architecture, programming, interfacing techniques.", prerequisites: [] },
  { code: "BHCS ZC328", name: "Introduction to IoT", units: 4, semester: 7, term: 1, category: "OPEN_ELECTIVE", description: "Introduction to IoT - IoT architectures, sensors, protocols, applications.", prerequisites: [] },
  { code: "BHCS ZC244", name: "Accounting for Managers", units: 3, semester: 7, term: 1, category: "OPEN_ELECTIVE", description: "Accounting for Managers - Financial statements, cost analysis, managerial accounting.", prerequisites: [] },
  { code: "BHCS ZC322", name: "Corporate Finance", units: 3, semester: 7, term: 1, category: "OPEN_ELECTIVE", description: "Corporate Finance - Financial decision making, valuation, capital structure.", prerequisites: [] },
  { code: "BHCS ZC323", name: "Investment Management", units: 3, semester: 7, term: 1, category: "OPEN_ELECTIVE", description: "Investment Management - Portfolio theory, risk management, investment strategies.", prerequisites: [] },
  { code: "BHCS ZC243", name: "Signals and Systems", units: 3, semester: 7, term: 1, category: "OPEN_ELECTIVE", description: "Signals and Systems - Signal processing, Fourier transforms, system analysis.", prerequisites: [] },
];

async function main() {
  console.log("Upserting all subjects (PDF complete)...");
  let created = 0, updated = 0;
  for (const s of allSubjects) {
    const existing = await prisma.subject.findUnique({ where: { code: s.code } });
    if (existing) {
      await prisma.subject.update({
        where: { code: s.code },
        data: {
          name: s.name,
          units: s.units,
          semester: s.semester,
          term: s.term,
          category: s.category,
          description: s.description || undefined,
          prerequisites: s.prerequisites || [],
          specialization: s.specialization || null,
          foundationOption: s.foundationOption ?? null,
          isMandatory: s.isMandatory || false,
        },
      });
      updated++;
    } else {
      await prisma.subject.create({
        data: {
          code: s.code,
          name: s.name,
          units: s.units,
          semester: s.semester,
          term: s.term,
          category: s.category,
          description: s.description,
          prerequisites: s.prerequisites || [],
          specialization: s.specialization || null,
          foundationOption: s.foundationOption || null,
          isMandatory: s.isMandatory || false,
        },
      });
      updated++;
    }
  }
  console.log(`Upserted ${updated} subjects. Total now: ${await prisma.subject.count()}`);

  // Seed specializations
  const specs = [
    { name: "Full-Stack", mandatoryCodes: ["BHCS ZC413","BHCS ZC419","BHCS ZC415","BHCS ZC432"], miniProjectCode: "BHCS ZC427T", prerequisiteCode: null, description: "Backend and API, Frontend, Cross-platform, Software Deployment + Mini Project" },
    { name: "Cloud", mandatoryCodes: ["BHCS ZC414","BHCS ZC422","BHCS ZC420","BHCS ZC430"], miniProjectCode: "BHCS ZC427T", prerequisiteCode: "BCS ZC237" },
    { name: "AIML", mandatoryCodes: ["BHCS ZC421","BHCS ZC412","BHCS ZC417","BHCS ZC434"], miniProjectCode: "BHCS ZC427T", prerequisiteCode: "BCS ZC312" },
  ];
  for (const sp of specs) {
    await prisma.specialization.upsert({
      where: { name: sp.name },
      update: { mandatoryCodes: sp.mandatoryCodes, miniProjectCode: sp.miniProjectCode, prerequisiteCode: sp.prerequisiteCode, description: sp.description },
      create: { name: sp.name, description: sp.description, mandatoryCodes: sp.mandatoryCodes, miniProjectCode: sp.miniProjectCode, prerequisiteCode: sp.prerequisiteCode },
    });
    console.log(`✓ Specialization ${sp.name}`);
  }
}

main().catch(e=>{ console.error(e); process.exit(1); }).finally(()=> prisma.$disconnect());
