import { useEffect, useState } from "react";
import { ArrowRight, Bell, BookOpen, CalendarDays, Check, ChevronRight, Clock3, Download, FileText, Github, Layers3, Menu, Upload, Users, X } from "lucide-react";
import PreviewSection from "./components/PreviewSection";

const github = "https://github.com/Naren456/Async";
const download = "https://github.com/Naren456/Async/releases/tag/android";
const webAppUrl = (import.meta.env.VITE_WEB_APP_URL || "http://localhost:8081").replace(/\/$/, "");
const loginUrl = `${webAppUrl}/auth/signin`;
const features = [
  [Check, "Smart assignment tracking", "Keep upcoming work, due dates, and completion in one academic timeline."],
  [CalendarDays, "Automatic calendar sync", "Bring supported Coursera ICS calendar deadlines into ASync automatically."],
  [Bell, "Local reminders", "Get a timely nudge before an important submission slips through the cracks."],
  [FileText, "Notes & resources", "Teachers publish materials; students open the PDFs they need inside the app."],
  [Users, "Role-based workspace", "Students and teachers each get tools that fit their everyday workflow."],
];
const tech = ["React Native", "Expo", "Node.js", "Express", "PostgreSQL", "Prisma", "Redux Toolkit", "NativeWind"];

function Button({ href, children, muted = false }) {
  return <a href={href} className={`inline-flex min-h-11 items-center justify-center gap-2 rounded-lg px-5 py-3 text-sm font-semibold transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-400 ${muted ? "border border-[#242832] bg-[#101216] text-[#F5F7FA] hover:border-[#46506a]" : "bg-blue-500 text-white hover:bg-blue-400"}`}>{children}</a>;
}

function Dashboard() {
  const rows = [["Database Systems", "Assignment 03", "Due tomorrow"], ["Machine Learning", "Project proposal", "Due Friday"], ["Operating Systems", "Lab submission", "Due Monday"]];
  return <div className="mx-auto w-full max-w-3xl rounded-xl border border-[#303541] bg-[#101216] p-2 shadow-2xl shadow-black/50 motion-safe:animate-[fade-in-up_0.8s_ease-out]"><div className="overflow-hidden rounded-lg border border-[#242832] bg-[#0c0e12]"><div className="flex h-10 items-center gap-2 border-b border-[#242832] px-4"><span className="h-2 w-2 rounded-full bg-[#4a5261]"/><span className="h-2 w-2 rounded-full bg-[#4a5261]"/><span className="h-2 w-2 rounded-full bg-[#4a5261]"/><span className="ml-3 text-xs text-[#9CA3AF]">ASync workspace</span></div><div className="grid min-h-[390px] grid-cols-[1fr] sm:grid-cols-[160px_1fr]"><aside className="hidden border-r border-[#242832] p-4 sm:block"><div className="mb-7 flex items-center gap-2 font-bold text-white"><span className="grid h-7 w-7 place-items-center rounded-md bg-blue-500"><BookOpen size={15}/></span>ASync</div>{["Dashboard", "Assignments", "Notes", "Calendar", "Settings"].map((x,i)=><div className={`mb-1 flex gap-2 rounded-md px-3 py-2 text-xs ${i===0?"bg-[#1a2130] text-white":"text-[#9CA3AF]"}`} key={x}><Layers3 size={14}/>{x}</div>)}</aside><main className="p-5 sm:p-6"><div className="mb-6 flex justify-between"><div><p className="text-xs text-[#9CA3AF]">Monday, 14 September</p><h3 className="mt-1 text-xl font-semibold text-white">Good morning 👋</h3></div><Bell className="text-[#9CA3AF]" size={17}/></div><div className="grid gap-3 lg:grid-cols-[1fr_145px]"><section><h4 className="mb-3 text-sm font-semibold text-white">Upcoming</h4>{rows.map(([course, task, due])=><div className="mb-2 flex gap-3 rounded-lg border border-[#242832] bg-[#101216] p-3" key={course}><span className="h-8 w-1 rounded-full bg-blue-400"/><div className="min-w-0 flex-1"><p className="text-xs font-medium text-[#F5F7FA]">{course}</p><p className="text-[11px] text-[#9CA3AF]">{task}</p></div><span className="text-[10px] text-[#9CA3AF]">{due}</span></div>)}</section><aside className="rounded-lg border border-[#242832] bg-[#101216] p-3"><p className="text-xs font-medium text-white">Today&apos;s progress</p><p className="mt-3 text-2xl font-semibold text-white">2 <span className="text-xs font-normal text-[#9CA3AF]">of 4</span></p><div className="mt-3 h-1.5 rounded-full bg-[#242832]"><div className="h-full w-1/2 bg-blue-500"/></div><div className="mt-6 grid grid-cols-7 gap-1 text-center text-[9px] text-[#9CA3AF]">{["M","T","W","T","F","S","S"].map((d,i)=><span key={i} className={i===0?"rounded bg-blue-500 py-1 text-white":"py-1"}>{d}</span>)}</div></aside></div></main></div></div></div>;
}

function App() {
  const [menu, setMenu] = useState(false), [scrolled, setScrolled] = useState(false);
  useEffect(()=>{const handler=()=>setScrolled(window.scrollY>12);window.addEventListener("scroll",handler,{passive:true});return()=>window.removeEventListener("scroll",handler)},[]);
  const links = [["Features","#features"],["How it works","#how-it-works"],["For Students","#students"],["For Teachers","#teachers"]];
  return <div className="min-h-screen overflow-x-hidden bg-[#08090B] text-[#F5F7FA] selection:bg-blue-500/40">
    <header className={`sticky top-0 z-50 border-b transition ${scrolled?"border-[#242832] bg-[#08090B]/95 backdrop-blur":"border-transparent bg-[#08090B]/80"}`}><nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><a href="#top" className="flex items-center gap-2 font-semibold text-white"><span className="grid h-8 w-8 place-items-center rounded-md bg-blue-500"><BookOpen size={17}/></span>ASync</a><div className="hidden gap-7 md:flex">{links.map(([l,h])=><a key={h} href={h} className="text-sm text-[#9CA3AF] hover:text-white">{l}</a>)}</div><div className="hidden items-center gap-4 md:flex"><a href={github} className="text-sm text-[#9CA3AF] hover:text-white"><Github className="mr-1 inline" size={16}/>GitHub</a><a href={loginUrl} className="text-sm font-medium text-[#F5F7FA] hover:text-blue-400">Login</a><Button href={download}>Get Started <ArrowRight size={15}/></Button></div><button aria-label="Toggle navigation" aria-expanded={menu} className="p-2 md:hidden" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></nav>{menu&&<div className="border-t border-[#242832] bg-[#101216] px-5 py-4 md:hidden">{links.map(([l,h])=><a onClick={()=>setMenu(false)} key={h} href={h} className="block py-3">{l}</a>)}<a href={loginUrl} className="block py-3 font-medium text-[#F5F7FA]">Login</a><Button href={download}>Get Started</Button></div>}</header>
    <main id="top">
      <section className="mx-auto grid max-w-7xl gap-12 px-5 pb-24 pt-20 lg:grid-cols-[.85fr_1.15fr] lg:items-center lg:px-8 lg:pb-32 lg:pt-28"><div className="motion-safe:animate-[fade-in-up_.7s_ease-out]"><p className="mb-6 text-xs font-semibold tracking-[.16em] text-blue-400">ACADEMIC PRODUCTIVITY, REIMAGINED</p><h1 className="max-w-xl text-5xl font-semibold leading-[1.04] tracking-[-.045em] text-white sm:text-6xl lg:text-7xl">Stay ahead of every deadline.<span className="block text-[#9CA3AF]">Without losing focus.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#9CA3AF]">ASync brings assignments, deadlines, notes, and academic resources into one focused workspace built for students and educators.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button href={download}>Get Started <ArrowRight size={16}/></Button><Button href="#features" muted>Explore ASync <ChevronRight size={16}/></Button></div><div className="mt-9 flex flex-wrap gap-x-5 gap-y-2 text-sm text-[#9CA3AF]"><span>Student-first</span><span>Cross-platform</span><span>Open source</span></div></div><Dashboard/></section>
      <section className="border-y border-[#242832] bg-[#101216]/40"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-20 lg:grid-cols-[1fr_auto_1fr] lg:items-center lg:px-8"><div><p className="text-xs font-semibold tracking-[.15em] text-blue-400">THE PROBLEM</p><h2 className="mt-4 max-w-lg text-3xl font-semibold tracking-tight text-white sm:text-4xl">Your academic life shouldn&apos;t live in five different places.</h2></div><div className="hidden h-20 w-px bg-[#242832] lg:block"/><div className="grid gap-3 text-sm text-[#9CA3AF] sm:grid-cols-[1fr_auto_1fr] sm:items-center"><div className="space-y-2"><p>Assignments in one platform</p><p>Notes in PDFs</p><p>Deadlines in calendars</p></div><ArrowRight className="mx-auto text-blue-400"/><div className="rounded-lg border border-blue-500/40 bg-blue-500/10 p-4 text-center font-medium text-white">ASync<br/><span className="text-xs font-normal text-[#9CA3AF]">one focused workspace</span></div></div></div></section>
      <section id="features" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><p className="text-xs font-semibold tracking-[.15em] text-blue-400">FEATURES</p><h2 className="mt-4 max-w-xl text-3xl font-semibold tracking-tight text-white sm:text-5xl">Everything you need to stay on track.</h2><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-12">{features.map(([Icon,title,copy],i)=><article key={title} className={`border border-[#242832] bg-[#101216] p-6 transition hover:-translate-y-1 hover:border-[#3b465e] ${i===0?"md:col-span-2 lg:col-span-7":i===1?"lg:col-span-5":i===2?"lg:col-span-4":i===3?"lg:col-span-5":"lg:col-span-3"}`}><Icon className="text-blue-400" size={21}/><h3 className="mt-10 text-lg font-medium text-white">{title}</h3><p className="mt-2 max-w-md text-sm leading-6 text-[#9CA3AF]">{copy}</p></article>)}</div></section>
      <section id="students"><PreviewSection/></section>
      <section id="teachers" className="border-y border-[#242832] bg-[#101216]/40"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-24 lg:grid-cols-2 lg:items-center lg:px-8"><div><p className="text-xs font-semibold tracking-[.15em] text-blue-400">FOR EDUCATORS</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-white sm:text-5xl">A simpler workflow for educators.</h2><p className="mt-5 max-w-lg leading-7 text-[#9CA3AF]">Manage subjects, upload PDF resources, and keep assignment information accurate for the cohorts you support.</p></div><div className="rounded-xl border border-[#242832] bg-[#08090B] p-5"><div className="flex justify-between border-b border-[#242832] pb-4"><span className="font-medium">Teacher workspace</span><span className="rounded bg-blue-500/15 px-2 py-1 text-xs text-blue-400">Admin</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="border border-[#242832] p-4"><Upload className="text-blue-400" size={19}/><p className="mt-6 text-sm text-white">Upload resource</p><p className="mt-1 text-xs text-[#9CA3AF]">PDF notes for your course</p></div><div className="border border-[#242832] p-4"><Users className="text-blue-400" size={19}/><p className="mt-6 text-sm text-white">Manage cohorts</p><p className="mt-1 text-xs text-[#9CA3AF]">Keep content relevant</p></div></div></div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><p className="text-xs font-semibold tracking-[.15em] text-blue-400">AUTOMATION</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-white sm:text-5xl">Your deadlines, automatically organized.</h2><div className="mt-12 grid gap-3 md:grid-cols-3 lg:grid-cols-6">{["Coursera / Calendar","ICS Calendar","ASync Backend","Assignment Processing","Student Dashboard","Local Reminder"].map((s,i)=><div key={s} className="border border-[#242832] bg-[#101216] p-4 text-sm"><span className="mb-8 block text-xs text-[#9CA3AF]">0{i+1}</span>{s}</div>)}</div></section>
      <section className="border-y border-[#242832] bg-[#101216]/40"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-2 lg:px-8"><div><p className="text-xs font-semibold tracking-[.15em] text-blue-400">DEEP FOCUS</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-white sm:text-5xl">Designed for deep focus.</h2><p className="mt-5 max-w-lg leading-7 text-[#9CA3AF]">Less noise. Fewer distractions. A workspace designed to help you see what matters next.</p></div><div className="border border-[#242832] bg-[#08090B] p-5"><div className="flex justify-between"><span className="text-sm font-medium">Next up</span><Clock3 size={16} className="text-blue-400"/></div><div className="mt-8 border-l-2 border-blue-500 pl-4"><p className="text-sm text-white">Database Systems — Assignment 03</p><p className="mt-1 text-xs text-[#9CA3AF]">Due tomorrow · 11:59 PM</p></div><p className="mt-7 text-xs text-[#9CA3AF]">One clear priority. No unnecessary noise.</p></div></div></section>
      <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><p className="text-xs font-semibold tracking-[.15em] text-blue-400">HOW IT WORKS</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-white sm:text-5xl">Make room for what matters.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{[["01","Connect","Get your academic workspace ready."],["02","Organize","Assignments, resources and deadlines come together automatically."],["03","Focus","Know what needs your attention next and stay ahead of deadlines."]].map(([n,t,c])=><div key={n} className="border-t border-[#3a4252] pt-5"><span className="text-sm text-blue-400">{n}</span><h3 className="mt-7 text-xl text-white">{t}</h3><p className="mt-2 text-sm leading-6 text-[#9CA3AF]">{c}</p></div>)}</div></section>
      <section className="border-y border-[#242832] bg-[#101216]/40"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><p className="text-xs font-semibold tracking-[.15em] text-blue-400">ENGINEERING</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-white sm:text-5xl">Built like a real product.</h2><div className="mt-10 flex flex-wrap gap-2">{tech.map(t=><span key={t} className="border border-[#242832] bg-[#08090B] px-3 py-2 text-sm text-[#9CA3AF]">{t}</span>)}</div><div className="mt-10 grid gap-4 md:grid-cols-2"><div className="border border-[#242832] p-5 text-sm text-[#9CA3AF]"><p className="font-medium text-white">Mobile App</p><p className="my-3 text-blue-400">↓</p><p>REST API</p><p className="my-3 text-blue-400">↓</p><p>Node.js / Express → Prisma → PostgreSQL</p></div><div className="border border-[#242832] p-5 text-sm text-[#9CA3AF]"><p className="font-medium text-white">Calendar Sync</p><p className="my-3 text-blue-400">↓</p><p>ICS Calendar</p><p className="my-3 text-blue-400">↓</p><p>Cron jobs → Assignment data</p></div></div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-24 text-center lg:px-8"><Github className="mx-auto text-blue-400" size={25}/><h2 className="mt-5 text-3xl font-semibold tracking-tight text-white sm:text-5xl">Built in the open.</h2><p className="mx-auto mt-5 max-w-xl leading-7 text-[#9CA3AF]">ASync is open source and built to evolve with the people who use it.</p><div className="mt-8"><Button href={github} muted><Github size={16}/>View on GitHub</Button></div></section>
      <section className="border-y border-[#242832] bg-[#101216]"><div className="mx-auto max-w-7xl px-5 py-24 text-center lg:px-8"><h2 className="text-3xl font-semibold tracking-tight text-white sm:text-5xl">Your next deadline is already closer than you think.</h2><p className="mx-auto mt-5 max-w-xl text-[#9CA3AF]">Bring your academic workflow into one focused workspace with ASync.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Button href={download}>Get Started <Download size={16}/></Button><Button href={github} muted>View on GitHub <Github size={16}/></Button></div></div></section>
    </main><footer className="mx-auto max-w-7xl px-5 py-12 lg:px-8"><div className="grid gap-10 md:grid-cols-4"><div><p className="font-semibold text-white">ASync</p><p className="mt-3 text-sm text-[#9CA3AF]">Academic productivity, built for focus.</p></div>{[["Product","Features","Students","Teachers","How it works"],["Resources","GitHub","Documentation","Installation"],["Project","Open Source","MIT License"]].map(([h,...ls])=><div key={h}><p className="text-sm font-medium text-white">{h}</p>{ls.map(l=><p key={l} className="mt-3 text-sm text-[#9CA3AF]">{l}</p>)}</div>)}</div><div className="mt-12 flex justify-between border-t border-[#242832] pt-6 text-sm text-[#9CA3AF]"><span>© 2026 ASync</span><span>MIT License</span></div></footer>
  </div>;
}
export default App;
